[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
[build]
command = "CI= npm run build"
