const colors = require('tailwindcss/colors')

module.exports = {
    purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'], darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            height: theme => ({
                '11/12': '91.666667%'
            }),
            spacing: {
                '128': '32rem',
                '135': '33.75rem',
                '140': '35rem',
                '150': '37.5rem',
                '160': '40rem',
                '170': '42.5rem',
                '180': '45rem',
                '190': '47.5rem',
                '200': '50rem',
            },
            colors: {
                inherit: colors.inherit,
                current: colors.current,
                transparent: colors.transparent,
                black: colors.black,
                white: colors.white,
                slate: colors.slate,
                gray: colors.gray,
                zinc: colors.zinc,
                neutral: colors.neutral,
                stone: colors.stone,
                red: colors.red,
                orange: colors.orange,
                amber: colors.amber,
                yellow: colors.yellow,
                lime: colors.lime,
                green: colors.green,
                emerald: colors.emerald,
                teal: colors.teal,
                cyan: colors.cyan,
                sky: colors.sky,
                blue: colors.blue,
                indigo: colors.indigo,
                violet: colors.violet,
                purple: colors.purple,
                fuchsia: colors.fuchsia,
                pink: colors.pink,
                rose: colors.rose,
                dimgray: "#616060",
            },
        },
        maxWidth: {
            '1/4': '25%',
            '1/2': '50%',
            '3/4': '75%',
        },
        maxHeight: {
            '0': '0',
            '1/4': '25%',
            '1/2': '50%',
            '3/4': '75%',
            'full': '100%',
        },
        minWidth: {
            '0': '0',
            '1/12': '8.33%',
            '2/12': '16.66%',
            '3/12': '25%',
            '4/12': '33.33%',
            '5/12': '41.66%',
            '6/12': '50%',
            '7/12': '58.33%',
            '8/12': '66.66%',
            '9/12': '75%',
            '10/12': '83.33%',
            '11/12': '91.66%',
            'full': '100%',
        },
        listStyleType: {
            none: 'none',
            disc: 'disc',
            decimal: 'decimal',
            square: 'square',
            roman: 'upper-roman',
        },
    },
    variants: {
        transitionProperty: ['responsive', 'motion-safe', 'motion-reduce'],
        extend: {
            visibility: ['hover', 'focus'],
        },
    },
    plugins: [],
}